<a href="https://colab.research.google.com/github/muhsintsn/python-project/blob/main/Statistics_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [2]:
import numpy as np
import numpy as pd
from scipy import stats

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [3]:
mean, std = 100, 15 # mean and standard deviation
samples = np.random.normal(mean, std, 1000)
samples

array([ 88.36431405,  88.99402937, 112.99478421, 108.9958198 ,
        48.12378167,  91.10053209,  98.11961154,  79.04382345,
       103.50961559, 108.24385732,  85.33050763,  81.71346522,
       108.18603867,  86.77782533,  93.02957521,  89.68917668,
        87.30898355, 120.95685934, 111.7627614 , 115.45391153,
        79.94044444,  85.13959265, 101.49006898, 100.78864949,
       111.59890278, 116.73502694, 102.59923476,  94.79077597,
        77.92236871, 102.92694051,  64.74592574,  95.42172257,
       106.65335427,  96.11667888, 119.7710769 ,  70.09941526,
        82.61736782,  87.39647247,  88.29011801,  90.8869276 ,
        85.59571061, 118.9060731 , 135.05265194, 105.03933323,
       102.04304131,  96.92801926,  93.8964929 ,  91.94829072,
        95.64524508,  73.68618658,  87.13212621, 101.02651142,
       110.68145025,  87.65241774,  88.54643248, 105.73955241,
       113.6939995 ,  93.92020225, 112.68863097, 103.34939749,
        83.77173816,  96.27021233, 130.26022942, 110.83

Compute the **mean**, **median**, and **mode**

In [6]:
mean = np.mean(samples)
mean

99.71271940642956

In [7]:
median = np.median(samples)
median

99.58276444758945

In [8]:
mode = stats.mode(samples)
mode

ModeResult(mode=array([48.12378167]), count=array([1]))

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [9]:
samples.min()

48.123781673624535

In [10]:
samples.max()

151.64689920998805

In [15]:
Q1 = np.percentile(samples, 25, interpolation = 'midpoint')
Q3 = np.percentile(samples, 75, interpolation = 'midpoint')
IQR = stats.iqr(samples, interpolation = 'midpoint')
print("Q1 :",Q1)
print("Q3 :", Q3)
print("IQR :", IQR)

Q1 : 90.05128921806515
Q3 : 109.71177259541193
IQR : 19.66048337734678


Compute the **variance** and **standard deviation**

In [16]:
std_dev = np.std(samples)
std_dev

14.804303407030421

In [17]:
variance = np.std(samples)**2
variance

219.16739936741254

Compute the **skewness** and **kurtosis**

In [18]:
skewness = stats.skew(samples)
skewness

-0.020270722301681348

In [19]:
kurtosis = stats.kurtosis(samples)
kurtosis

0.2233299904564996

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [20]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [21]:
y = np.random.randint(10, size=(1,10))
y

array([[1, 4, 6, 2, 6, 4, 6, 5, 1, 5]])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [33]:
r = np.corrcoef(x, y)
r


array([[1.        , 0.75864029],
       [0.75864029, 1.        ]])

## Pandas Correlation Calculation

Run the code below

In [28]:
import numpy as np
import pandas as pd
from scipy import stats

In [36]:
x1 = pd.Series(range(10, 20))
y1 = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [37]:
r = stats.pearsonr(x1, y1)
r

(0.758640289091187, 0.010964341301680813)

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [38]:
stats.spearmanr(x1,y1, axis= None)

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [40]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [41]:
tips = sns.load_dataset("tips")
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [42]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [43]:
tips.corr()

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000

In [44]:
tips.corr(method="pearson")

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000